# batch config

label:                'Ticha'
description:          'An international effort to document and promote Zapotec languages and knowledge through workshops, events, and online resources provided to the public at no cost'
attribution:          'Access Provided by Ticha'

source_dir:           'ticha' # 'src/data'
image_output_format:  'jpg'

presentation_api_url: 'https://ticha-iiif.s3.us-east-1.amazonaws.com'
image_api_url:        'https://awy5mcn5cgxb3cxtpcyf7cp6pu0lgvmp.lambda-url.us-east-1.on.aws/iiif/3'

records:
  label_key: 'title'
  file: 'src/documents.csv'
  # defaults:
  #   logo: ''

# batch:
#   records:        
#     source: 'src/documents.csv'
#   assets:         
#     source: '/Volumes/mn119/zapotec/doc_images' # 'src/data'
#   output:
#     image_format: 'jpg'

# iiif:
#   api_version:           3
#   presentation_api_url: 'https://ticha-iiif.s3.us-east-1.amazonaws.com'
#   image_api_url:        'https://awy5mcn5cgxb3cxtpcyf7cp6pu0lgvmp.lambda-url.us-east-1.on.aws/iiif/3/'
#   collection: 
#     label:               'Ticha'
#     description:         'An international effort to document and promote Zapotec languages and knowledge through workshops, events, and online resources provided to the public at no cost'
#     attribution:          'Access Provided by Ticha'
#   manifests:
#     label_key: 'title'
#     metadata_keys: []
#     # defaults: